theme: jekyll-theme-minimal
title: GitHub Documentation Demo
description: A demonstration of GitHub documentation setup
baseurl: "/test-docs"

# GitHub Pages specific settings
plugins:
  - jekyll-remote-theme