remote_theme: just-the-docs/just-the-docs
title: GitHub Documentation Demo
description: A demonstration of GitHub documentation setup
baseurl: "/test-docs"

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# Enable navigation order
nav_sort: case_sensitive

# GitHub Pages specific settings
plugins:
  - jekyll-remote-theme

# Additional settings
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/

# Remove footer and all related elements
footer_content: ""
back_to_top: false
back_to_top_text: ""
last_edit_timestamp: false
last_edit_time_format: ""
gh_edit_link: false
gh_edit_link_text: ""
gh_edit_repository: ""
gh_edit_branch: ""
gh_edit_view_mode: ""