theme: jekyll-theme-minimal
title: GitHub Documentation Demo
description: A demonstration of GitHub documentation setup
baseurl: "/test-docs"

# Navigation
header_pages:
  - getting-started.md
  - contributing.md

# GitHub Pages specific settings
plugins:
  - jekyll-remote-theme

# Additional settings
show_downloads: true
google_analytics: # your GA tracking ID here (optional)