remote_theme: just-the-docs/just-the-docs
title: GitHub Documentation Demo
description: A demonstration of GitHub documentation setup
show_downloads: false
color_scheme: dark
baseurl: "/test-docs"

# Build settings
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

# Just the Docs specific settings
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "https://github.com/numbered-com/test-docs"

# GitHub Pages specific settings
plugins:
  - jekyll-remote-theme